### ISSUE TITLE
[gov cloud] Azure Key Vault URL is malformed

### ISSUE THREAD

**Issue by Akshay-Phapale** [jenkinsci/azure-keyvault-plugin#102]
### Version report

Jenkins and plugins versions report:

```
latest
```

- What Operating System are you using (both controller, and any agents involved in the problem)?

```
Ubuntu
```

### Reproduction steps

- Step 1 Create Key vault and spn on azure
- Step 2 Add spn in jenkins and verify it (Verification successful)
- step 3 Go to jenkins system configuration add Key vault URL and select the spn from the credentails and click "test connection"
### Results

Expected result:
Connection successful and azure key vault sync to jenkins

Actual result:

```
<!-- What was the actual result? -->
2021-11-22 18:02:17.237+0000 [id=518650]        SEVERE  c.a.c.util.logging.ClientLogger#performLogging: The Azure Key Vault url is malformed.
2021-11-22 18:02:17.237+0000 [id=518650]        WARNING o.j.p.a.AzureCredentialsProvider#fetchCredentials: Error retrieving secrets from Azure KeyVault: The Azure Key Vault url is malformed.
java.net.MalformedURLException: no protocol:
        at java.net.URL.<init>(URL.java:611)
        at java.net.URL.<init>(URL.java:508)
        at java.net.URL.<init>(URL.java:457)
        at com.azure.security.keyvault.secrets.SecretClientBuilder.vaultUrl(SecretClientBuilder.java:213)
Caused: java.lang.IllegalArgumentException: The Azure Key Vault url is malformed.
        at com.azure.security.keyvault.secrets.SecretClientBuilder.vaultUrl(SecretClientBuilder.java:215)
        at com.microsoft.azure.util.AzureCredentials.createKeyVaultClient(AzureCredentials.java:511)
        at com.microsoft.jenkins.keyvault.SecretClientCache.createClient(SecretClientCache.java:46)
        at com.github.benmanes.caffeine.cache.LocalLoadingCache.lambda$newMappingFunction$2(LocalLoadingCache.java:141)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2413)
        at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1853)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2411)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2394)
        at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:108)
        at com.github.benmanes.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:54)
        at com.microsoft.jenkins.keyvault.SecretClientCache.get(SecretClientCache.java:27)
        at org.jenkinsci.plugins.azurekeyvaultplugin.AzureCredentialsProvider.fetchCredentials(AzureCredentialsProvider.java:109)
        at org.jenkinsci.plugins.azurekeyvaultplugin.AzureCredentialsProvider.lambda$new$0(AzureCredentialsProvider.java:53)
        at com.github.benmanes.caffeine.cache.CacheLoader.reload(CacheLoader.java:166)
        at com.github.benmanes.caffeine.cache.CacheLoader.lambda$asyncReload$2(CacheLoader.java:190)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by timja** [comment]
What url format did you use? It says it’s missing a protocol

**Comment by timja** [comment]
Likely fixed by https://github.com/jenkinsci/azure-keyvault-plugin/pull/118
