### ISSUE TITLE
Errors in latest versions together with azure-ad plugin

### ISSUE THREAD

**Issue by luka5** [jenkinsci/azure-keyvault-plugin#103]
### Version report

<details>
  <summary>Jenkins and plugins versions report:</summary>
  
```
Jenkins: 2.303.3
OS: Linux - 5.4.0-1059-azure
---
ace-editor:1.1
ansicolor:0.7.5
antisamy-markup-formatter:1.1
apache-httpcomponents-client-4-api:4.5.13-1.0
authentication-tokens:1.4
authorize-project:1.4.0
azure-ad:185.v3b416408dcb1
azure-credentials:198.vf9c2fdfde55c
azure-keyvault:131.v867845ef6ae9
azure-sdk:70.v63f6a95999a7
blueocean:1.25.2
blueocean-autofavorite:1.2.4
blueocean-bitbucket-pipeline:1.25.2
blueocean-commons:1.25.2
blueocean-config:1.25.2
blueocean-core-js:1.25.2
blueocean-dashboard:1.25.2
blueocean-display-url:2.4.1
blueocean-events:1.25.2
blueocean-git-pipeline:1.25.2
blueocean-github-pipeline:1.25.2
blueocean-i18n:1.25.2
blueocean-jwt:1.25.2
blueocean-personalization:1.25.2
blueocean-pipeline-api-impl:1.25.2
blueocean-pipeline-editor:1.25.2
blueocean-pipeline-scm-api:1.25.2
blueocean-rest:1.25.2
blueocean-rest-impl:1.25.2
blueocean-web:1.25.2
bootstrap4-api:4.6.0-3
bootstrap5-api:5.1.3-3
bouncycastle-api:2.25
branch-api:2.7.0
caffeine-api:2.9.2-29.v717aac953ff3
checks-api:1.7.2
cloudbees-bitbucket-branch-source:726.vb0c1ea6c9336
cloudbees-folder:6.16
cloudfoundry:2.3.2
command-launcher:1.2
conditional-buildstep:1.4.1
config-file-provider:3.8.2
configuration-as-code:1.54
credentials:2.6.1
credentials-binding:1.27
display-url-api:2.3.5
docker-commons:1.17
durable-task:493.v195aefbb0ff2
echarts-api:5.2.2-1
envinject:2.4.0
envinject-api:1.8
favorite:2.3.3
font-awesome-api:5.15.4-3
git:4.10.0
git-client:3.10.0
git-server:1.10
github:1.34.1
github-api:1.133
github-branch-source:2.11.3
google-oauth-plugin:1.0.6
handlebars:3.0.8
handy-uri-templates-2-api:2.1.8-1.0
hsts-filter-plugin:1.0
htmlpublisher:1.28
jackson2-api:2.13.0-230.v59243c64b0a5
javadoc:1.6
jdk-tool:1.0
jenkins-design-language:1.25.2
jira:3.6
jjwt-api:0.11.2-9.c8b45b8bb173
job-dsl:1.78.1
jquery3-api:3.6.0-2
jsch:0.1.55.2
junit:1.53
kubernetes:1.30.10
kubernetes-client-api:5.4.1
kubernetes-credentials:0.9.0
kubernetes-credentials-provider:0.20
ldap:2.7
lockable-resources:2.12
mailer:1.34
mapdb-api:1.0.9.0
matrix-auth:2.6.8
matrix-project:1.19
maven-plugin:3.15.1
mercurial:2.16
metrics:4.0.2.8
momentjs:1.1.1
oauth-credentials:0.5
okhttp-api:4.9.2-20211102
parameterized-trigger:2.42
pipeline-build-step:2.15
pipeline-github-lib:1.0
pipeline-graph-analysis:1.11
pipeline-input-step:2.12
pipeline-milestone-step:1.3.2
pipeline-model-api:1.9.3
pipeline-model-definition:1.9.3
pipeline-model-extensions:1.9.3
pipeline-rest-api:2.19
pipeline-stage-step:2.5
pipeline-stage-tags-metadata:1.9.3
pipeline-stage-view:2.19
pipeline-utility-steps:2.10.0
plain-credentials:1.7
plugin-util-api:2.5.1
popper-api:1.16.1-2
popper2-api:2.10.2-1
prometheus:2.0.10
pubsub-light:1.16
resource-disposer:0.16
role-strategy:3.2.0
run-condition:1.5
scm-api:2.6.5
script-security:1.78
snakeyaml-api:1.29.1
sonar:2.14
sse-gateway:1.24
ssh-agent:1.23
ssh-credentials:1.19
sshd:3.1.0
structs:1.23
subversion:2.15.1
token-macro:267.vcdaea6462991
trilead-api:1.0.13
variant:1.4
windows-slaves:1.0
workflow-aggregator:2.6
workflow-api:2.47
workflow-basic-steps:2.24
workflow-cps:2633.v6baeedc13805
workflow-cps-global-lib:548.v9085a486966a
workflow-durable-task-step:1097.veac1aacfbda8
workflow-job:2.42
workflow-multibranch:2.26
workflow-remote-loader:1.5
workflow-scm-step:2.13
workflow-step-api:2.24
workflow-support:3.8
ws-cleanup:0.39
```
</details>

- What Operating System are you using (both controller, and any agents involved in the problem)?

```
Azure Kubernetes Service with Ubuntu nodes
```

### Reproduction steps

- Configure a credential and the plugin with Configuration as Code
  ```
  credentials:
    system:
      domainCredentials:
        - credentials:
          - azure:
              azureEnvironmentName: "Azure"
              clientId: "${AZKV_APP_ID}"
              clientSecret: "${AZKV_CLIENT_SECRET}"
              description: "Azure service principal to access an azure key vault"
              id: "service-principal-keyvault-access"
              scope: GLOBAL
              subscriptionId: "${AZKV_SUBSCRIPTION_ID}"
              tenant: "${AZKV_TENANT}"
  unclassified:
    azureKeyVault:
      keyVaultURL: "${AZKV_URL}"
      credentialID: "service-principal-keyvault-access"
  ```
- start Jenkins with azure-keyvault plugin version `126` or newer
- in around 80% the cases, we get the following output and afterwards **everything works fine**
  ```
  2021-11-30 07:44:48.911+0000 [id=53]    SEVERE  c.a.c.util.logging.ClientLogger#performLogging: 'credential' cannot be null.
  2021-11-30 07:44:48.912+0000 [id=53]    WARNING o.j.p.a.AzureCredentialsProvider#fetchCredentials: Error retrieving secrets from Azure KeyVault: 'credential' cannot be null.
  java.lang.NullPointerException: 'credential' cannot be null.
          at com.azure.security.keyvault.secrets.SecretClientBuilder.credential(SecretClientBuilder.java:233)
          at com.microsoft.azure.util.AzureCredentials.createKeyVaultClient(AzureCredentials.java:512)
          at com.microsoft.jenkins.keyvault.SecretClientCache.createClient(SecretClientCache.java:46)
          at com.github.benmanes.caffeine.cache.LocalLoadingCache.lambda$newMappingFunction$2(LocalLoadingCache.java:141)
          at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2413)
          at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1853)
          at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2411)
          at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2394)
          at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:108)
          at com.github.benmanes.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:54)
          at com.microsoft.jenkins.keyvault.SecretClientCache.get(SecretClientCache.java:27)
          at org.jenkinsci.plugins.azurekeyvaultplugin.AzureCredentialsProvider.fetchCredentials(AzureCredentialsProvider.java:109)
          at org.jenkinsci.plugins.azurekeyvaultplugin.AzureCredentialsProvider.lambda$new$0(AzureCredentialsProvider.java:53)
          at com.github.benmanes.caffeine.cache.CacheLoader.lambda$asyncLoad$0(CacheLoader.java:104)
          at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
          at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596)
          at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
          at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
          at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
          at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
  ...
  2021-11-30 07:45:27.728+0000 [id=53]    INFO    c.a.c.util.logging.ClientLogger#performLogging: Azure Identity => getToken() result for scopes [https://vault.azure.net/.default]: SUCCESS
  ```
  In this case, our `azure-ad` plugin login works fine as well an we get:
  ```
  2021-11-30 07:48:40.658+0000 [id=9]     INFO    c.m.j.azuread.AzureSecurityRealm#doFinishLogin: Requesting oauth code time = 449 ms
  ...
  2021-11-30 07:48:47.333+0000 [id=139]   INFO    c.a.c.util.logging.ClientLogger#performLogging: Azure Identity => getToken() result for scopes [https://graph.microsoft.com/.default]: SUCCESS
  ...
  2021-11-30 07:48:52.656+0000 [id=9]     INFO    c.m.j.azuread.AzureSecurityRealm#lambda$doFinishLogin$3: Fetch user details with sub: xxxxxxx***
  ```
- In ~20% the cases we don't see these messages.
  - We are then also unable to login using the `azure-ad` plugin. It does not terminate or print any error message from neither `azure-keyvault` nor `azure-ad` plugin. While logging in we see just
    ```
    2021-11-09 16:10:11.821+0000 [id=16]	INFO	c.m.j.azuread.AzureSecurityRealm#doFinishLogin: Requesting oauth code time = 384 ms
    ```

### Results

Expected result:
- Login works
- Keyvault credentials as synced

Actual result:
- Login fails
- Not sure if the credentials are synced

### Research Results
So far I tried to understand it myself and provide a fix to the project. Since the `azure-ad` login fails as well, I first had a close look into that plugin. I've then figured out that this error started showing up with `azure-keyvault` version 126, 129 or 131 being installed. It works fine with version 123 or without the plugin being installed.

I'm not sure, if and how the exception is related to this, but it always shows up if it works.

I've figured out, that the login gets stock during the `graphIntegration` in https://github.com/jenkinsci/azure-ad-plugin/blob/185.v3b416408dcb1/src/main/java/com/microsoft/jenkins/azuread/AzureSecurityRealm.java#L401-L404 I've disabled it for testing - the login was success then.

I've created multiple identical Jenkins instances in our Kubernetes and restarted all of them several times. It sometimes happens - sometimes it does not.

It's unclear to me how those two plugins are related during the runtime of Jenkins. What are they sharing? Does this make any sense? Does the exception give us a clue?

For the moment we stick with version `123` and everything is running just fine.

Thanks a lot for your help!

**Comment by luka5** [comment]
I was able to reproduce the same behavior today with Jenkins `2.332.3`, `azure-ad:218.v90f6a_980b_a_61` and the latest version of this plugin: `136.veb1d1296db97`. After switching back to `123.v1aba71c2d365` it works fine again.

Anyone any idea? Is there someone also using the `azure-ad` and the `azure-keyvault` plugin?

**Comment by timja** [comment]
the Azure SDK is to in theory prevent plugin conflicts so that installing a plugin shouldn't affect another one, all shared (more than one plugin uses them) libraries from Azure should be bundled there

A newer Azure SDK can cause issues if there's a bug in them and it affects the plugins.

If you can try rolling back just azure sdk it might help but you may have issues with plugins requiring certain versions of it

**Comment by timja** [comment]
> Can we ensure that the azure-keyvault plugin starts after the configuration-as-code plugin has finished? As long as we can not, I'll keep using the env based approach and try to resolve:

No it needs to start before hand as it provides a credentials provider that is used in configuration as code.

That's the reason that environment variables and system properties are supported for configuring it.

Ideally you should use Managed identity for authenticating so that there's no credentials in the command line / environment

**Comment by luka5** [comment]
Thanks for your input @timja, I was able to "resolve" this issue by configuring this plugin via ENVs instead of CasC.

What do you think, should we add a hint on the README? Something like: 
> *Note* It is not supported to configure the credential in the same moment with CasC as well. Please use one of the other options or ensure to create the credential with CasC before configuring this plugin.

That would've helped me a lot. What do you think?

**Comment by timja** [comment]
Sure, maybe something like:

> Note: It is not supported to configure the credential provider with the configuration as code plugin and using credentials from it at the same time. Please use one of the other options (system properties, environment variables) instead if you want to use this feature.
