### ISSUE TITLE
A connection to https://***.vault.azure.net/ was leaked

### ISSUE THREAD

**Issue by timja** [jenkinsci/azure-keyvault-plugin#37]
```
Feb 08, 2020 5:44:36 PM okhttp3.internal.platform.Platform log
WARNING: A connection to https://***.vault.azure.net/ was leaked. Did you forget to close a response body?
java.lang.Throwable: response.body().close()
	at okhttp3.internal.platform.Platform.getStackTraceForCloseable(Platform.java:148)
	at okhttp3.RealCall.captureCallStackTrace(RealCall.java:89)
	at okhttp3.RealCall.execute(RealCall.java:73)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:180)
	at 

````

It seems to have been fixed in: https://github.com/Azure/azure-sdk-for-java/issues/2790
released in: https://github.com/Azure/azure-libraries-for-java/releases/tag/v1.22.0

Currently we are using 1.19.0, dependency tree:
```
[INFO] |  +- com.microsoft.azure:azure:jar:1.19.0:compile
[INFO] |  |  +- com.microsoft.azure:azure-client-runtime:jar:1.6.4:compile
[INFO] |  |  |  \- com.microsoft.rest:client-runtime:jar:1.6.4:compile
[INFO] |  |  |     +- com.squareup.okhttp3:logging-interceptor:jar:3.11.0:compile
[INFO] |  |  |     +- com.squareup.okhttp3:okhttp-urlconnection:jar:3.11.0:compile
[INFO] |  |  |     +- com.squareup.retrofit2:converter-jackson:jar:2.4.0:compile
[INFO] |  |  |     +- com.fasterxml.jackson.datatype:jackson-datatype-joda:jar:2.9.4:compile
```

Latest is: 1.31.0

_Originally posted by @timja in https://github.com/jenkinsci/azure-keyvault-plugin/pull/33#issuecomment-583778795_

Note: this is pulled in by the azure-credentials plugin and just updating the version didn't seem to work, I got descriptor missing erorrs

**Comment by timja** [comment]
cc @gavinfish
