### ISSUE TITLE
Connection to <Vault url> was leaked warnings in Jenkins log

### ISSUE THREAD

**Issue by jaheikki** [jenkinsci/azure-keyvault-plugin#58]
### Your checklist for this issue

- [x] Jenkins version

- [x] Plugin version

- [x] OS

Jenkins version: 2.226
Plugin version: 1.9
OS: Linux (Kubernetes container)

### Description

There's a lot of warnings  in Jenkins log (see clip below). Assuming it is related to 'azure-keyvault-plugin'?  I have seen problems related Jenkins master pod NOT starting Jenkins slave pod (in Kubernetes Jenkins) and at the same time Jenkins log is full of 'A connection to <Vault url> was leaked' printouts. Don't know if problems are related...

```
020-03-30 08:05:45.149+0000 [id=36]	INFO	o.c.j.p.k.KubernetesCloud#provision: Excess workload after pending Kubernetes agents: 1
2020-03-30 08:05:45.149+0000 [id=36]	INFO	o.c.j.p.k.KubernetesCloud#provision: Template for label my-jenkins-slave: Kubernetes Pod Template
2020-03-30 08:05:55.162+0000 [id=30]	INFO	hudson.slaves.NodeProvisioner#lambda$update$6: Kubernetes Pod Template provisioning successfully completed. We have now 2 computer(s)
2020-03-30 08:05:55.191+0000 [id=127]	INFO	o.c.j.p.k.KubernetesLauncher#launch: Created Pod: my-kube-jenkins/default-65d6f
2020-03-30 08:05:55.259+0000 [id=135]	INFO	o.internal.platform.Platform#log: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
2020-03-30 08:06:38.360+0000 [id=127]	INFO	o.c.j.p.k.KubernetesLauncher#launch: Pod is running: my-kube-jenkins/default-65d6f
2020-03-30 08:06:38.366+0000 [id=127]	INFO	o.c.j.p.k.KubernetesLauncher#launch: Waiting for agent to connect (0/100): default-65d6f
2020-03-30 08:06:38.792+0000 [id=203]	INFO	h.TcpSlaveAgentListener$ConnectionHandler#run: Accepted JNLP4-connect connection #1 from /172.19.3.26:59048
2020-03-30 08:06:39.371+0000 [id=127]	INFO	o.c.j.p.k.KubernetesLauncher#launch: Waiting for agent to connect (1/100): default-65d6f
2020-03-30 08:06:40.377+0000 [id=127]	INFO	o.c.j.p.k.KubernetesLauncher#launch: Waiting for agent to connect (2/100): default-65d6f
2020-03-30 08:06:41.382+0000 [id=127]	INFO	o.c.j.p.k.KubernetesLauncher#launch: Waiting for agent to connect (3/100): default-65d6f
2020-03-30 08:06:42.387+0000 [id=127]	INFO	o.c.j.p.k.KubernetesLauncher#launch: Waiting for agent to connect (4/100): default-65d6f
2020-03-30 08:06:44.671+0000 [id=135]	INFO	o.internal.platform.Platform#log: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
2020-03-30 08:07:02.832+0000 [id=234]	INFO	o.internal.platform.Platform#log: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
2020-03-30 08:07:02.930+0000 [id=237]	INFO	c.m.a.a.AuthenticationAuthority#doInstanceDiscovery: [Correlation ID: 40d3e994-1af4-4216-b927-2da0b8e8870f] Instance discovery was successful
2020-03-30 08:07:03.166+0000 [id=234]	INFO	o.internal.platform.Platform#log: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
2020-03-30 08:07:03.450+0000 [id=234]	INFO	o.internal.platform.Platform#log: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
2020-03-30 08:07:03.478+0000 [id=241]	INFO	c.m.a.a.AuthenticationAuthority#doInstanceDiscovery: [Correlation ID: fe622a5b-e3d0-40cf-a367-ba2b3e8e728d] Instance discovery was successful
2020-03-30 08:07:59.109+0000 [id=205]	WARNING	o.j.r.u.AnonymousClassWarnings#warn: Attempt to (de-)serialize anonymous class org.jenkinsci.plugins.durabletask.FileMonitoringTask$FileMonitoringController$1 in file:/var/jenkins_home/plugins/durable-task/WEB-INF/lib/durable-task.jar; see: https://jenkins.io/redirect/serialization-of-anonymous-classes/
2020-03-30 08:12:03.303+0000 [id=235]	WARNING	o.internal.platform.Platform#log: A connection to https://my-vault.azure.net/ was leaked. Did you forget to close a response body?
java.lang.Throwable: response.body().close()
	at okhttp3.internal.platform.Platform.getStackTraceForCloseable(Platform.java:148)
	at okhttp3.RealCall.captureCallStackTrace(RealCall.java:116)
	at okhttp3.RealCall.execute(RealCall.java:88)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:188)
	at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:40)
	at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:24)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:10423)
	at rx.Observable.subscribe(Observable.java:10390)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:443)
	at rx.observables.BlockingObservable.single(BlockingObservable.java:340)
	at com.microsoft.azure.keyvault.implementation.KeyVaultClientBaseImpl.getSecrets(KeyVaultClientBaseImpl.java:3926)
	at org.jenkinsci.plugins.azurekeyvaultplugin.AzureCredentialsProvider.fetchCredentials(AzureCredentialsProvider.java:109)
	at com.google.common.base.Suppliers$ExpiringMemoizingSupplier.get(Suppliers.java:173)
	at org.jenkinsci.plugins.azurekeyvaultplugin.AzureCredentialsProvider.getCredentials(AzureCredentialsProvider.java:64)
	at com.cloudbees.plugins.credentials.CredentialsProvider.getCredentials(CredentialsProvider.java:1163)
	at com.cloudbees.plugins.credentials.CredentialsProvider.getCredentials(CredentialsProvider.java:1238)
	at com.cloudbees.plugins.credentials.CredentialsProvider.lookupCredentials(CredentialsProvider.java:565)
	at com.cloudbees.plugins.credentials.CredentialsProvider.findCredentialById(CredentialsProvider.java:922)
	at com.cloudbees.plugins.credentials.CredentialsProvider.findCredentialById(CredentialsProvider.java:866)
	at org.jenkinsci.plugins.credentialsbinding.MultiBinding.getCredentials(MultiBinding.java:144)
	at org.jenkinsci.plugins.credentialsbinding.impl.StringBinding.bindSingle(StringBinding.java:62)
	at org.jenkinsci.plugins.credentialsbinding.Binding.bind(Binding.java:150)
	at org.jenkinsci.plugins.credentialsbinding.impl.BindingStep$Execution2.doStart(BindingStep.java:135)
	at org.jenkinsci.plugins.workflow.steps.GeneralNonBlockingStepExecution.lambda$run$0(GeneralNonBlockingStepExecution.java:77)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by timja** [comment]
Fixed in 2.0, see https://github.com/jenkinsci/azure-keyvault-plugin/issues/37

**Comment by jaheikki** [comment]
Thanks, 2.0 seems not be available yet.

**Comment by timja** [comment]
> Thanks, 2.0 seems not be available yet.

it's been released, it can take a few hours to get synced to all mirrors, if you want to try it now you can use https://ci.jenkins.io/job/Plugins/job/azure-keyvault-plugin/job/master/68/artifact/org/jenkins-ci/plugins/azure-keyvault/2.1-rc104.ef3a5eb4413f/azure-keyvault-2.1-rc104.ef3a5eb4413f.hpi
