### ISSUE TITLE
Document how to use system assigned identity

### ISSUE THREAD

**Issue by ilons** [jenkinsci/azure-keyvault-plugin#68]
### Your checklist for this issue

- [x] Jenkins version: N/A

- [x] Plugin version: N/A

- [x] OS: N/A

### Description

When running on VMs in Azure, it would be really good to be able to use Azure SystemAssigned Identity on the instance in addition to user managed identities.
Is this something which is already supported (and which I missed to find in the documentation), or would it be a feature worth implemementing?

**Comment by timja** [comment]
Can you try it? The UAMI docs probably is equivalent for system assigned as well

**Comment by ilons** [comment]
> Can you try it? The UAMI docs probably is equivalent for system assigned as well

I tried to:
* Installed plugin
* Went to `Configure System`
* Entered the Key Vault URL
* Clicked `Test Connection`

This gave me: 
```
null
java.lang.NullPointerException	at java.util.Objects.requireNonNull(Objects.java:203)	at com.azure.security.keyvault.secrets.SecretClientBuilder.credential(SecretClientBuilder.java:192)	at com.microsoft.azure.util.AzureCredentials.createKeyVaultClient(AzureCredentials.java:524)	at org.jenkinsci.plugins.azurekeyvaultplugin.AzureKeyVaultGlobalConfiguration.doTestConnection(AzureKeyVaultGlobalConfiguration.java:215)	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:396)	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:408)	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:212)	at org.kohsuke.stapler.SelectionInterceptedFunction$Adapter.invoke(SelectionInterceptedFunction.java:36)	at org.kohsuke.stapler.verb.HttpVerbInterceptor.invoke(HttpVerbInterceptor.java:48)	at org.kohsuke.stapler.SelectionInterceptedFunction.bindAndInvoke(SelectionInterceptedFunction.java:26)	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:145)	at org.kohsuke.stapler.MetaClass$11.doDispatch(MetaClass.java:536)	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:766)	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:898)	at org.kohsuke.stapler.MetaClass$4.doDispatch(MetaClass.java:281)	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:766)	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:898)	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:694)	at org.kohsuke.stapler.Stapler.service(Stapler.java:240)	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:763)	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1633)	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154)	at jenkins.telemetry.impl.UserLanguages$AcceptLanguageFilter.doFilter(UserLanguages.java:129)	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)	at jenkins.security.ResourceDomainFilter.doFilter(ResourceDomainFilter.java:76)	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:157)	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1609)	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:153)	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1609)	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:90)	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1609)	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:51)	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1609)	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1609)	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1609)	at jenkins.security.SuspiciousRequestFilter.doFilter(SuspiciousRequestFilter.java:36)	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1609)	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:561)	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:578)	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1612)	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434)	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1582)	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)	at org.eclipse.jetty.server.Server.handle(Server.java:516)	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556)	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773)	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905)	at java.lang.Thread.run(Thread.java:748)
```

For SystemAssigned Identities there is no name or credentials to define, so I left the credentials drop-down at `- none -`.

**Comment by timja** [comment]
You still need to define a credential

create one of these:

![image](https://user-images.githubusercontent.com/21194782/107615901-e88c0b00-6c44-11eb-82dc-99ef55c5c392.png)

**Comment by ilons** [comment]
Creating a credential with empty value for the ID field does indeed work :+1: 

Thank you very much for the help!

Adding this to the documentation would make sense I think.

**Comment by ilons** [comment]
Also, having the possibility to configure the plugin to use SystemAssigned Identity explicitly would make sense, as that way it would be possible to avoid configuring a dummy credential for the plugin to use.

**Comment by timja** [comment]
because of how the credentials system works it needs that credential.

This startup property would likely do it for you automatically:

```
-Djenkins.azure-keyvault.uami.enabled=true
```

**Comment by ilons** [comment]
> because of how the credentials system works it needs that credential.
> 
> This startup property would likely do it for you automatically:
> 
> ```
> -Djenkins.azure-keyvault.uami.enabled=true
> ```

I'll try that as well, thank you :+1:
