### ISSUE TITLE
Unable to access credentials when running on worker

### ISSUE THREAD

**Issue by ilons** [jenkinsci/azure-keyvault-plugin#73]
### Version report

Jenkins and plugins versions report:

```
Jenkins: 2.277.1
OS: Linux - 5.10.19-100.fc32.x86_64
---
...
script-security:1.76
workflow-support:3.8
plain-credentials:1.7
envinject:2.4.0
scm-api:2.6.4
swarm:3.25
jdk-tool:1.0
command-launcher:1.2
pipeline-milestone-step:1.3.2
junit:1.49
github-branch-source:2.10.2
font-awesome-api:5.15.2-2
plugin-util-api:2.0.0
workflow-durable-task-step:2.38
workflow-job:2.40
pipeline-stage-view:2.19
git-server:1.9
echarts-api:5.0.1-1
workflow-api:2.41
azure-credentials:4.0.6
token-macro:2.15
bouncycastle-api:2.16.0
versionnumber:1.9
jquery3-api:3.5.1-3
credentials:2.3.15
handlebars:1.1.1
azure-keyvault:2.2
github-api:1.123
pipeline-stage-tags-metadata:1.8.4
pipeline-build-step:2.13
bootstrap4-api:4.6.0-2
workflow-cps:2.90
checks-api:1.6.0
branch-api:2.6.3
envinject-api:1.7
job-dsl:1.77
build-name-setter:2.1.0
jjwt-api:0.11.2-9.c8b45b8bb173
durable-task:1.35
workflow-aggregator:2.6
workflow-multibranch:2.22
popper-api:1.16.1-2
lockable-resources:2.10
git-client:3.6.0
snakeyaml-api:1.27.0
workflow-scm-step:2.12
ssh-credentials:1.18.1
matrix-project:1.18
okhttp-api:3.14.9
structs:1.22
pipeline-model-extensions:1.8.4
workflow-cps-global-lib:2.18
pipeline-graph-analysis:1.10
apache-httpcomponents-client-4-api:4.5.13-1.0
cloudbees-folder:6.15
github:1.33.1
pipeline-input-step:2.12
pipeline-model-definition:1.8.4
trilead-api:1.0.13
credentials-binding:1.24
pipeline-stage-step:2.5
mailer:1.33
pipeline-rest-api:2.19
pipeline-model-api:1.8.4
jackson2-api:2.12.1
momentjs:1.1.1
workflow-step-api:2.23
ace-editor:1.1
display-url-api:2.3.4
workflow-basic-steps:2.23
jsch:0.1.55.2
git:4.6.0
```

- What Operating System are you using (both controller, and any agents involved in the problem)?

```
Master: Debian (docker base: jenkins/jenkins:2.277.1-lts-slim)
Workers: Debian Buster (docker base: openjdk:8u242-slim-buster) 
```

### Reproduction steps

- Create a job to be executed on worker
- Configure job with git scm using azure-keyvault-plugin credentials 
- Run job on worker

### Results

Expected result:
Job runs, checking out the git repository in the process

Actual result:
An exception are thrown when the worker tries to checkout the git repo:
```
Building remotely on 4eae87ad2d34 (swarm docker) in workspace /app/workspace/***redacted***
The recommended git tool is: NONE
using credential git-pat
Cloning the remote Git repository
Using shallow clone with depth 1
Cloning repository https://github.com/***redacted***.git
 > git init /app/workspace/***redacted*** # timeout=10
Fetching upstream changes from https://github.com/***redacted***.git
 > git --version # timeout=10
 > git --version # 'git version 2.20.1'
using GIT_ASKPASS to set credentials https://***redacted***.vault.azure.net/secrets/git-pat
FATAL: Jenkins.instance is missing. Read the documentation of Jenkins.getInstanceOrNull to see what you are doing wrong.
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from jenkins_swarm_1.jenkins_default/10.10.22.3:42578
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1800)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
		at hudson.remoting.Channel.call(Channel.java:1001)
		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:146)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
		at java.lang.reflect.Method.invoke(Unknown Source)
		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:132)
		at com.sun.proxy.$Proxy91.execute(Unknown Source)
		at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1221)
		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1299)
		at hudson.scm.SCM.checkout(SCM.java:505)
		at hudson.model.AbstractProject.checkout(AbstractProject.java:1204)
		at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:636)
		at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
		at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:508)
		at hudson.model.Run.execute(Run.java:1907)
		at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
		at hudson.model.ResourceController.execute(ResourceController.java:97)
		at hudson.model.Executor.run(Executor.java:429)
java.lang.IllegalStateException: Jenkins.instance is missing. Read the documentation of Jenkins.getInstanceOrNull to see what you are doing wrong.
	at jenkins.model.Jenkins.get(Jenkins.java:775)
	at com.cloudbees.plugins.credentials.CredentialsProvider.lookupCredentials(CredentialsProvider.java:409)
	at com.microsoft.azure.util.AzureCredentials.getCredentialById(AzureCredentials.java:532)
	at com.microsoft.jenkins.keyvault.BaseSecretCredentials$SecretGetter$1.getKeyVaultSecret(BaseSecretCredentials.java:78)
	at com.microsoft.jenkins.keyvault.BaseSecretCredentials.getKeyVaultSecret(BaseSecretCredentials.java:61)
	at org.jenkinsci.plugins.azurekeyvaultplugin.AzureKeyVaultUsernamePasswordCredentials.getPassword(AzureKeyVaultUsernamePasswordCredentials.java:35)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.createPasswordFile(CliGitAPIImpl.java:2190)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:2009)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$500(CliGitAPIImpl.java:84)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:573)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:802)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:161)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:154)
	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:376)
	at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:119)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE
```

**Comment by ilons** [comment]
Looking into it, it seems as if the problem lies down in https://github.com/jenkinsci/azure-credentials-plugin, which are using `Jenkins.getInstance()`: https://github.com/jenkinsci/azure-credentials-plugin/search?q=jenkins.getInstance
This would not work when running on a worker afaik.
If I understood the google results properly, We need to serialize/deserialize the credentials, and send them to the worker from the master.
Looking for how this could be done I stumbled across: https://github.com/viglesiasce/google-source-plugin/blob/ee78ebf7cb615eae2dc5c66b4e410b50f6903938/src/main/java/com/google/jenkins/plugins/source/GoogleRobotUsernamePassword.java

**Comment by ilons** [comment]
Does anyone have experience on writing distributed plugins and could point me in the right direction?
The documentation is quite sparse: https://wiki.jenkins.io/display/JENKINS/Making+your+plugin+behave+in+distributed+Jenkins

**Comment by timja** [comment]
@chriskilding have you hit this in the AWS plugin?

**Comment by chriskilding** [comment]
Yeah I remember users hitting credential object serialisation errors when their Jenkins setup was distributed i.e. workers on different boxes. I had to add extra logic to my custom AWS-backed credential implementations to make it work in distributed mode, to get around the fact that the AWS client could not be serialised. I might still have that stuff in the plugin code.

Also, just like here, because the Jenkins test harness only works in local mode, it lets you access any Jenkins variable you like including ones that aren't available in distributed mode. As a result I wasn't able to see the bug in advance by writing tests; I only learned about it when users reported it.

**Comment by timja** [comment]
Would be good if you have a link to that

**Comment by chriskilding** [comment]
Here we go...

One of my implementations of the standard credential types is here: https://github.com/jenkinsci/aws-secrets-manager-credentials-provider-plugin/blob/master/src/main/java/io/jenkins/plugins/credentials/secretsmanager/factory/username_password/AwsUsernamePasswordCredentials.java

The corresponding `CredentialsSnapshotTaker` implementation for that type is here: https://github.com/jenkinsci/aws-secrets-manager-credentials-provider-plugin/blob/master/src/main/java/io/jenkins/plugins/credentials/secretsmanager/factory/username_password/AwsUsernamePasswordCredentialsSnapshotTaker.java

**Comment by chriskilding** [comment]
IIRC Jenkins will call the snapshot method at the start of any pipeline job, to ensure the credential's secret value is only looked up once. If there is no custom snapshot implementation, the default implementation just returns a reference to the existing credentials object; that's why we have to override it with our own implementations.

**Comment by ilons** [comment]
I've tried looking at how to implement this in the current plugin, but there is simply too many aspects of it that I don't understand for me to do this in a reasonable way.
If this is perceived as something not too complicated, could someone help me out with it?

**Comment by timja** [comment]
If you've got any questions happy to help, otherwise I'll try get to this at some point.

Integration tests which reproduce this would be very useful...

Example from azure-container-agent plugin:
https://github.com/jenkinsci/azure-container-agents-plugin/pull/66
