### ISSUE TITLE
Error retrieving secrets "Azure KeyVault: Unknown type: App Regisration"

### ISSUE THREAD

**Issue by dg4101** [jenkinsci/azure-keyvault-plugin#98]
### Version report

Jenkins and plugins versions report:

```
Jenkins 2.318
Plugin 131.v867845ef6ae9
```

- What Operating System are you using (both controller, and any agents involved in the problem)?

```
Linux
```

### Reproduction steps

- Step 1 Install plugin
- Step 2 Restart Jenkins

### Results

Expected result:

Be able to retrieve secret from key vault

Actual result:
Exception Thrown

Error retrieving secrets from Azure KeyVault: Unknown type: App Regisration
java.lang.IllegalStateException: Unknown type: App Regisration
	at org.jenkinsci.plugins.azurekeyvaultplugin.AzureCredentialsProvider.fetchCredentials(AzureCredentialsProvider.java:141)
	at org.jenkinsci.plugins.azurekeyvaultplugin.AzureCredentialsProvider.lambda$new$0(AzureCredentialsProvider.java:53)
	at com.github.benmanes.caffeine.cache.CacheLoader.lambda$asyncLoad$0(CacheLoader.java:104)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by timja** [comment]
It sounds like you have a secret with a tag with the value `type: App Registration` in your key vault?

Is that used for anything? or automatically created maybe.

I guess there's a couple of fixes we could do here:
1. Ignore unknown types, maybe logging it
2. Change the type tag to be a `jenkins-credential-type` tag

**Comment by dg4101** [comment]
Thank you for tips. You are right about the secret with the specific tag. After changing the tag value to e.g. Secret, it started working with Plugin 131.v867845ef6ae9

**Comment by timja** [comment]
I'll close this for now and see if anyone else hits it

**Comment by dg4101** [comment]
Sorry my test was immature. With Secret as tag value, it still failed

Error retrieving secrets from Azure KeyVault: Unknown type: Secret
java.lang.IllegalStateException: Unknown type: Secret
	at org.jenkinsci.plugins.azurekeyvaultplugin.AzureCredentialsProvider.fetchCredentials(AzureCredentialsProvider.java:141)
	at org.jenkinsci.plugins.azurekeyvaultplugin.AzureCredentialsProvider.lambda$new$0(AzureCredentialsProvider.java:53)
	at com.github.benmanes.caffeine.cache.CacheLoader.lambda$asyncLoad$0(CacheLoader.java:104)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by timja** [comment]
`string` or `username` are the accepted types right now

**Comment by dg4101** [comment]
I ended up removing type from the tag. Now it's confirmed working.
